### ISSUE TITLE
Small suggestions for document_create_from_html 

### ISSUE THREAD

**Issue by hleegwater** [burgerga/rspacer#3]
1. I'm not sure if we should allow it, but for now: if sections are missing, the function document_create_from_html cannot upload a document. This means that one might 
2. It would make more sense to me to use the qmd/Rmd yaml header for the author and date than a section within the document. For example

```
---
title: "Cool title"
author: "It's meeeeee"
date: "`r Sys.Date()`"
```

instead of 

```
## Title

`{r} rmarkdown::metadata$title`

## Date (dd-MM-yyyy)

`{r} format(Sys.time(), format = "%d-%m-%Y")`
```

to be continued :)

**Comment by burgerga** [comment]
I totally agree with 2, and I tried it, but didn't get it too work :D (maybe now after 3 months I have more clarity of mind to fix it)

And your first point is not complete it seems...

**Comment by hleegwater** [comment]
Hmm, I don't get emails from github, sorry for the late reply. I'll start working on a function that can replace/append one section in a remote doc. That can solve my incomplete point 1 (that sometimes you don't want to have all headers from an RSpace Template, just one or two).
